export const QUERY_KEYS = {
  CATEGORIES: ["categories"],
  CATEGORY: (id: number) => ["categories", id],
  MENU_ITEMS: ["menu-items"],
  MENU_ITEM: (id: number) => ["menu-items", id],
  TABLES: ["tables"],
  TABLE: (id: number) => ["tables", id],
  CUSTOMERS: ["customers"],
  CUSTOMER: (id: number) => ["customers", id],
  DELIVERY_RIDERS: ["delivery-riders"],
  DELIVERY_RIDER: (id: number) => ["delivery-riders", id],
  ORDERS: ["orders"],
  ORDER: (id: number) => ["orders", id],
  HOLD_ORDERS: ["orders", "hold"],
  RETURNS: ["returns"],
  RETURN: (id: number) => ["returns", id],
  EXPENSES: ["expenses"],
  EXPENSE: (id: number) => ["expenses", id],
  REPORTS_DAILY: (date: string) => ["reports", "daily", date],
  REPORTS_MONTHLY: (year: number, month: number) => ["reports", "monthly", year, month],
  REPORTS_CUSTOM: (start: string, end: string) => ["reports", "custom", start, end],
  REPORTS_DELIVERY: (start: string, end: string) => ["reports", "delivery", start, end],
  REPORTS_EXPENSES: (start: string, end: string) => ["reports", "expenses", start, end],
  REPORTS_RETURNS: (start: string, end: string) => ["reports", "returns", start, end],
  SETTINGS: ["settings"],
  AUDIT_LOGS: ["audit-logs"],
  AUDIT_LOG: (id: number) => ["audit-logs", id],
} as const;
