ALTER TABLE Settings ADD COLUMN PrinterName TEXT DEFAULT '';
ALTER TABLE Settings ADD COLUMN PaperWidth INTEGER DEFAULT 80;
ALTER TABLE Settings ADD COLUMN PrinterCopies INTEGER DEFAULT 1;
ALTER TABLE Settings ADD COLUMN PrinterEnabled INTEGER NOT NULL DEFAULT 1;
